apiVersion: apps/v1
kind: Deployment

metadata:
  name: intelliera-devops-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: intelliera-devops-app

  template:
    metadata:
      labels:
        app: intelliera-devops-app

    spec:
      containers:
        - name: intelliera-devops-app
          image: 396608803308.dkr.ecr.us-east-1.amazonaws.com/intelliera-devops-app:1.0

          ports:
            - containerPort: 8080

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"
